version: '3.8'

services:
  mcp_server_lks:
    image: mcp_server_lks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:8000"
    # volumes:
    #   - ./app:/app  
    networks:
      - ai-core-tools_mattin-network
networks:
  ai-core-tools_mattin-network:
    external: true
