services:
  anonymization_server:
    image: anonymization_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
    networks:
      - candidate_eval_app-network

networks:
  candidate_eval_app-network:
    external: true